/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
 // systemDesignSidebar: ['system-design/system-design-articles'],
 systemDesignSidebar: [{type: 'autogenerated', dirName: 'system-design'}],
 softwareArchitectureSidebar : [{type: 'autogenerated', dirName: 'software-architecture'}],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['event-driven-architecture/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
